# **MACHINE LEARNING**

Predict the "fuel-type" of cars from the given dataset

**IMPORTING LIBRARIES**



In [0]:
from google.colab import files
import numpy as np
import seaborn as sns
from sklearn.datasets import load_iris
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split as tts
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import LinearSVC
from sklearn.cluster import KMeans
import numpy
from sklearn.metrics import classification_report,confusion_matrix
import matplotlib.pyplot as plt

**IMPORTING DATASET**



In [0]:
url1 = "https://raw.githubusercontent.com/reubence/Google-DSC-Workshop-2020/master/datasets/Automobile_data.csv"
data = pd.read_csv(url1)

In [0]:
data.head()

symboling normalized-losses         make  ... city-mpg highway-mpg  price
0          3                 ?  alfa-romero  ...       21          27  13495
1          3                 ?  alfa-romero  ...       21          27  16500
2          1                 ?  alfa-romero  ...       19          26  16500
3          2               164         audi  ...       24          30  13950
4          2               164         audi  ...       18          22  17450

[5 rows x 26 columns]

In [0]:
data.isnull().values.any() #Checking if there are any NULL values

False

In [0]:
data["normalized-losses"].value_counts()
#there are ? as missing values

?      41
161    11
91      8
150     7
104     6
134     6
128     6
102     5
103     5
74      5
94      5
65      5
85      5
95      5
168     5
148     4
118     4
106     4
122     4
93      4
154     3
115     3
101     3
83      3
137     3
125     3
119     2
113     2
81      2
129     2
153     2
89      2
164     2
197     2
110     2
188     2
108     2
158     2
87      2
194     2
192     2
145     2
98      1
90      1
142     1
256     1
78      1
186     1
77      1
107     1
121     1
231     1
Name: normalized-losses, dtype: int64

In [0]:
data["fuel-type"].value_counts()
#there are ? as missing values

gas       185
diesel     20
Name: fuel-type, dtype: int64

In [0]:
missing_values = ["?"]
data1 = pd.read_csv(url1, na_values = missing_values)
data1.head()

symboling  normalized-losses         make  ... city-mpg highway-mpg    price
0          3                NaN  alfa-romero  ...       21          27  13495.0
1          3                NaN  alfa-romero  ...       21          27  16500.0
2          1                NaN  alfa-romero  ...       19          26  16500.0
3          2              164.0         audi  ...       24          30  13950.0
4          2              164.0         audi  ...       18          22  17450.0

[5 rows x 26 columns]

In [0]:
data1.isnull().mean() * 100 #Sometimes we want to get an overview of how much % of the dataset is actually missing

symboling             0.00000
normalized-losses    20.00000
make                  0.00000
fuel-type             0.00000
aspiration            0.00000
num-of-doors          0.97561
body-style            0.00000
drive-wheels          0.00000
engine-location       0.00000
wheel-base            0.00000
length                0.00000
width                 0.00000
height                0.00000
curb-weight           0.00000
engine-type           0.00000
num-of-cylinders      0.00000
engine-size           0.00000
fuel-system           0.00000
bore                  1.95122
stroke                1.95122
compression-ratio     0.00000
horsepower            0.97561
peak-rpm              0.97561
city-mpg              0.00000
highway-mpg           0.00000
price                 1.95122
dtype: float64

In [0]:
data1.isnull().sum().sum() #We can also find Total Number of NULL values in the dataset instead of %

59

In [0]:
data1.isnull().sum() #Here we are checking NULL values column-wise

symboling             0
normalized-losses    41
make                  0
fuel-type             0
aspiration            0
num-of-doors          2
body-style            0
drive-wheels          0
engine-location       0
wheel-base            0
length                0
width                 0
height                0
curb-weight           0
engine-type           0
num-of-cylinders      0
engine-size           0
fuel-system           0
bore                  4
stroke                4
compression-ratio     0
horsepower            2
peak-rpm              2
city-mpg              0
highway-mpg           0
price                 4
dtype: int64

In [0]:
data1.get_dtype_counts()

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: FutureWarning: `get_dtype_counts` has been deprecated and will be removed in a future version. For DataFrames use `.dtypes.value_counts()
  """Entry point for launching an IPython kernel.


float64    11
int64       5
object     10
dtype: int64

In [0]:
categories = data1.select_dtypes(include = ['object']).columns.tolist()
categories
 #here numeric rows are of object types so we need to remember to change them
#Everything looks fine as object variables dont contain any numbers

['make',
 'fuel-type',
 'aspiration',
 'num-of-doors',
 'body-style',
 'drive-wheels',
 'engine-location',
 'engine-type',
 'num-of-cylinders',
 'fuel-system']

In [0]:
numeric = data1.select_dtypes(include = ['float64']).columns.tolist() 
numeric
#here numeric rows are of object types so we need to remember to change them

['normalized-losses',
 'wheel-base',
 'length',
 'width',
 'height',
 'bore',
 'stroke',
 'compression-ratio',
 'horsepower',
 'peak-rpm',
 'price']

In [0]:
data1['normalized-losses'] = data1['normalized-losses'].fillna(data1['normalized-losses'].median())

In [0]:
data1["num-of-doors"].value_counts()

four    114
two      89
Name: num-of-doors, dtype: int64

In [0]:
# data1['num-of-doors'] = data1['num-of-doors'].fillna("four")
data1.dropna(subset=['num-of-doors'])


symboling  normalized-losses         make  ... city-mpg highway-mpg    price
0            3              115.0  alfa-romero  ...       21          27  13495.0
1            3              115.0  alfa-romero  ...       21          27  16500.0
2            1              115.0  alfa-romero  ...       19          26  16500.0
3            2              164.0         audi  ...       24          30  13950.0
4            2              164.0         audi  ...       18          22  17450.0
..         ...                ...          ...  ...      ...         ...      ...
200         -1               95.0        volvo  ...       23          28  16845.0
201         -1               95.0        volvo  ...       19          25  19045.0
202         -1               95.0        volvo  ...       18          23  21485.0
203         -1               95.0        volvo  ...       26          27  22470.0
204         -1               95.0        volvo  ...       19          25  22625.0

[203 rows x 26 columns]

In [0]:
data1['bore'] = data1['bore'].fillna(data1['bore'].median())

In [0]:
data1['horsepower'] = data1['horsepower'].fillna(data1['horsepower'].median())

In [0]:
data1['stroke'] = data1['stroke'].fillna(data1['stroke'].median())

In [0]:
data1['peak-rpm'] = data1['peak-rpm'].fillna(data1['peak-rpm'].median())

In [0]:
data1['price'] = data1['price'].fillna(data1['price'].median())

In [0]:
data1.head(10)

symboling  normalized-losses         make  ... city-mpg highway-mpg    price
0          3              115.0  alfa-romero  ...       21          27  13495.0
1          3              115.0  alfa-romero  ...       21          27  16500.0
2          1              115.0  alfa-romero  ...       19          26  16500.0
3          2              164.0         audi  ...       24          30  13950.0
4          2              164.0         audi  ...       18          22  17450.0
5          2              115.0         audi  ...       19          25  15250.0
6          1              158.0         audi  ...       19          25  17710.0
7          1              115.0         audi  ...       19          25  18920.0
8          1              158.0         audi  ...       17          20  23875.0
9          0              115.0         audi  ...       16          22  10295.0

[10 rows x 26 columns]

In [0]:
data1.isna().sum().sum()
#no more null values :D

2

In [0]:
Y = data1["fuel-type"]
Y.head()

0    gas
1    gas
2    gas
3    gas
4    gas
Name: fuel-type, dtype: object

In [0]:
X= pd.get_dummies(data = data1, columns = categories)
# X.drop("fuel-type")
X.head()
#One-Hot-Encoding the variables

symboling  normalized-losses  ...  fuel-system_spdi  fuel-system_spfi
0          3              115.0  ...                 0                 0
1          3              115.0  ...                 0                 0
2          1              115.0  ...                 0                 0
3          2              164.0  ...                 0                 0
4          2              164.0  ...                 0                 0

[5 rows x 76 columns]

In [0]:
X.isna().sum().sum()

0

# **Handling the Imbalance**

In [0]:
X_train, X_test, y_train, y_test = tts(X, Y, test_size=0.3, random_state=42)

In [0]:
from imblearn.over_sampling import SMOTE

/usr/local/lib/python3.6/dist-packages/sklearn/externals/six.py:31: FutureWarning: The module is deprecated in version 0.21 and will be removed in version 0.23 since we've dropped support for Python 2.7. Please rely on the official version of six (https://pypi.org/project/six/).
  "(https://pypi.org/project/six/).", FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/utils/deprecation.py:144: FutureWarning: The sklearn.neighbors.base module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.neighbors. Anything that cannot be imported from sklearn.neighbors is now part of the private API.
  warnings.warn(message, FutureWarning)


In [0]:
sm = SMOTE(random_state=2)

In [0]:
X_sm, Y_sm = sm.fit_sample(X_train, y_train)

/usr/local/lib/python3.6/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function safe_indexing is deprecated; safe_indexing is deprecated in version 0.22 and will be removed in version 0.24.
  warnings.warn(msg, category=FutureWarning)


In [0]:
X_sm #["fuel-type"].value_counts()
#there are ? as missing values

array([[ -1.        ,  65.        , 102.4       , ...,   1.        ,
          0.        ,   0.        ],
       [  1.        , 115.        , 102.7       , ...,   1.        ,
          0.        ,   0.        ],
       [ -1.        ,  65.        , 102.4       , ...,   0.        ,
          0.        ,   0.        ],
       ...,
       [  0.64572052, 108.21993459,  98.31570961, ...,   0.        ,
          0.        ,   0.        ],
       [  1.77165481,  96.39762447,  97.47125889, ...,   0.        ,
          0.        ,   0.        ],
       [  0.        , 153.93597915, 108.86746373, ...,   0.        ,
          0.        ,   0.        ]])

# **Support-Vector Machines**

In [0]:
svc = LinearSVC()
svc.fit(X_train, y_train)

/usr/local/lib/python3.6/dist-packages/sklearn/svm/_base.py:947: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


LinearSVC(C=1.0, class_weight=None, dual=True, fit_intercept=True,
          intercept_scaling=1, loss='squared_hinge', max_iter=1000,
          multi_class='ovr', penalty='l2', random_state=None, tol=0.0001,
          verbose=0)

In [0]:
svc.score(X_test,y_test)

0.8870967741935484

In [0]:
predictions3 = svc.predict(X_test)
print(classification_report(y_test,predictions3))

              precision    recall  f1-score   support

      diesel       0.56      0.62      0.59         8
         gas       0.94      0.93      0.93        54

    accuracy                           0.89        62
   macro avg       0.75      0.78      0.76        62
weighted avg       0.89      0.89      0.89        62



In [0]:
print(confusion_matrix(y_test,predictions3))

[[ 5  3]
 [ 4 50]]


# **Logistic Regression**

In [0]:
clf = LogisticRegression()
clf.fit(X_train,y_train)

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [0]:
clf.score(X_test,y_test)

1.0

In [0]:
predictions = clf.predict(X_test)
print(classification_report(y_test,predictions))

              precision    recall  f1-score   support

      diesel       1.00      1.00      1.00         8
         gas       1.00      1.00      1.00        54

    accuracy                           1.00        62
   macro avg       1.00      1.00      1.00        62
weighted avg       1.00      1.00      1.00        62



In [0]:
print(confusion_matrix(y_test,predictions))

[[ 8  0]
 [ 0 54]]


# **KNN**

In [0]:
Y

0         gas
1         gas
2         gas
3         gas
4         gas
        ...  
200       gas
201       gas
202       gas
203    diesel
204       gas
Name: fuel-type, Length: 205, dtype: object

In [0]:
neigh = KNeighborsClassifier(n_neighbors=2)
neigh.fit(X, Y)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=2, p=2,
                     weights='uniform')

In [0]:
neigh.score(X_test,y_test)

0.9354838709677419

In [0]:
predicted = neigh.predict(X_test)
print(classification_report(y_test,predicted))

              precision    recall  f1-score   support

      diesel       0.67      1.00      0.80         8
         gas       1.00      0.93      0.96        54

    accuracy                           0.94        62
   macro avg       0.83      0.96      0.88        62
weighted avg       0.96      0.94      0.94        62



In [0]:
predicted

array(['diesel', 'gas', 'gas', 'gas', 'diesel', 'gas', 'diesel', 'gas',
       'gas', 'diesel', 'gas', 'gas', 'gas', 'diesel', 'gas', 'gas',
       'gas', 'gas', 'gas', 'gas', 'gas', 'gas', 'gas', 'gas', 'gas',
       'gas', 'gas', 'gas', 'gas', 'gas', 'diesel', 'gas', 'diesel',
       'gas', 'gas', 'diesel', 'gas', 'gas', 'gas', 'gas', 'diesel',
       'diesel', 'gas', 'gas', 'gas', 'gas', 'gas', 'gas', 'diesel',
       'gas', 'gas', 'gas', 'diesel', 'gas', 'gas', 'gas', 'gas', 'gas',
       'gas', 'gas', 'gas', 'gas'], dtype=object)

In [0]:
print(confusion_matrix(y_test,predicted))

[[ 8  0]
 [ 4 50]]


In [0]:
solution = pd.DataFrame({'Y-pred':[y_test]})
y_train_file = pd.DataFrame({'Y-train':[y_train]})
x_train_file = pd.DataFrame({'x_train':[X_train]})
x_test_file = pd.DataFrame({'x_test':[X_test]})



In [0]:
solution.to_csv("solution.csv", index=False) # write to csv

In [0]:
y_train_file.to_csv("Y_train.csv", index=False) # write to csv

In [0]:
x_test_file.to_csv("X_test.csv", index=False) # write to csv

In [0]:
x_train_file.to_csv("X_train.csv", index=False) # write to csv